DROP DATABASE IF EXISTS todo_db;
CREATE DATABASE todo_db;

USE todo_db;

CREATE TABLE todos  (
  id INT NOT NULL AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
);

SELECT * FROM todos;